services:
  mysql:
    image: mysql:latest
    container_name: mysql-blog-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: web_app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - ./database/mysql/create_tables.sql:/docker-entrypoint-initdb.d/init.sql
